# .gitlab-ci.yml

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.sikademo.com

job:
  script:
    - echo docker build . -t $IMAGE
    - echo helm install ... --set host=$HOST
