# .gitlab-ci.yml

stages:
  - build
  - deploy

build:
  stage: build
  script: echo Build ...
  only:
    - master
    - merge_requests

deploy:
  stage: deploy
  script: echo Deploy ...
  only:
    - master
  when: manual
  allow_failure: false
