# .gitlab-ci.yml

stages:
  - build
  - test
  - deploy

foo:
  stage: build
  script: echo Build! && sleep 10

bar:
  stage: test
  script: echo Test1!

baz:
  stage: test
  script: echo Test2! && sleep 10

deploy:
  stage: deploy
  script: echo Test2!
