job:
  script:
    - echo docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    - echo helm install ... --set host=$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.sikademo.com
