# .gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: echo build && sleep 10


test:
  stage: test
  script: echo test && sleep 10


deploy:
  stage: deploy
  script: echo build
